import { NavLink, ServiceCard, DiseaseCategory, Doctor, PatientStory, MedicineProduct, FAQItem } from "@/types";

export const NAV_LINKS: NavLink[] = [
  { label: "Home", href: "/" },
  { label: "Digital Health Assistant", href: "/digital-assistant", badge: "New" },
  { label: "Online Consultation", href: "/consult" },
  { label: "Ayurveda", href: "/ayurveda" },
  { label: "Homeopathy", href: "/homeopathy" },
  { label: "Medicine Delivery", href: "/pharmacy" },
  { label: "Wellness Store", href: "/store" },
];

export const TRUST_INDICATORS = [
  {
    value: "1.2M+",
    label: "Patients Healed",
    description: "Successful recovery stories across India",
  },
  {
    value: "500+",
    label: "Expert Clinicians",
    description: "Ayurveda & Homeopathy specialists",
  },
  {
    value: "100%",
    label: "Authentic Medicines",
    description: "Lab-tested, certified organic formulations",
  },
  {
    value: "4.8★",
    label: "Patient Satisfaction",
    description: "Based on 50,000+ verified ratings",
  },
];

export const SERVICES: ServiceCard[] = [
  {
    id: "digital-assistant",
    title: "Digital Health Consultation",
    description: "Get instant wellness analysis, symptom evaluation, and personalized natural recommendations driven by expert clinical models.",
    iconName: "BrainCircuit",
    href: "/digital-assistant",
    category: "digital-health",
  },
  {
    id: "online-consult",
    title: "Online Doctor Consultation",
    description: "Connect via high-definition video or audio calls with highly qualified Ayurvedic and Homeopathic physicians within 15 minutes.",
    iconName: "Video",
    href: "/consult",
    category: "doctor-consult",
  },
  {
    id: "ayurveda-care",
    title: "Ayurvedic Treatment Plans",
    description: "Root-cause healing using natural therapies, customized diet charts, lifestyle corrections, and authentic herbal formulations.",
    iconName: "Leaf",
    href: "/ayurveda",
    category: "ayurveda",
  },
  {
    id: "homeopathy-care",
    title: "Homeopathic Care",
    description: "Safe, side-effect-free, and highly individualized treatments that stimulate your body's natural defense mechanism.",
    iconName: "Sparkles",
    href: "/homeopathy",
    category: "homeopathy",
  },
  {
    id: "medicine-delivery",
    title: "Express Medicine Delivery",
    description: "Order prescribed medicines and general wellness products directly to your doorstep with guaranteed temperature-controlled shipping.",
    iconName: "Truck",
    href: "/pharmacy",
    category: "medicine-delivery",
  },
  {
    id: "wellness-store",
    title: "Healthcare E-Commerce",
    description: "Shop a curated collection of organic food, daily supplements, natural skin care, personal care, and specialized herbal teas.",
    iconName: "ShoppingBag",
    href: "/store",
    category: "wellness-ecommerce",
  },
];

export const DISEASE_CATEGORIES: DiseaseCategory[] = [
  {
    id: "digestion",
    name: "Digestion & Gut Health",
    iconName: "Activity",
    slug: "digestion",
    treatmentCount: "120k+ Recoveries",
  },
  {
    id: "joint-pain",
    name: "Joint & Bone Pain",
    iconName: "Bone",
    slug: "joint-pain",
    treatmentCount: "95k+ Recoveries",
  },
  {
    id: "hair-skin",
    name: "Hair & Skin Care",
    iconName: "Sparkle",
    slug: "hair-skin",
    treatmentCount: "150k+ Recoveries",
  },
  {
    id: "diabetes",
    name: "Diabetes Management",
    iconName: "HeartPulse",
    slug: "diabetes",
    treatmentCount: "80k+ Recoveries",
  },
  {
    id: "weight-management",
    name: "Weight & Metabolism",
    iconName: "Scale",
    slug: "weight-management",
    treatmentCount: "110k+ Recoveries",
  },
  {
    id: "stress-anxiety",
    name: "Stress & Mental Peace",
    iconName: "Brain",
    slug: "stress-anxiety",
    treatmentCount: "75k+ Recoveries",
  },
  {
    id: "women-health",
    name: "Women's Wellness",
    iconName: "Flower",
    slug: "womens-health",
    treatmentCount: "90k+ Recoveries",
  },
  {
    id: "respiratory",
    name: "Respiratory Care",
    iconName: "Wind",
    slug: "respiratory",
    treatmentCount: "65k+ Recoveries",
  },
];

export const WHY_CHOOSE_US = [
  {
    id: "dual-pathway",
    title: "Synergy of Ayurveda & Homeopathy",
    description: "We are India's first platform to blend ancient Ayurvedic knowledge with modern Homeopathy, offering a complete natural recovery strategy.",
    iconName: "HeartHandshake",
  },
  {
    id: "digital-screening",
    title: "Smart Pre-Screening",
    description: "Our proprietary digital wellness guide analyzes your symptoms and matches you with the ideal doctor, optimizing diagnostic accuracy and consultation time.",
    iconName: "Cpu",
  },
  {
    id: "certified-doctors",
    title: "Rigorous Doctor Verification",
    description: "Every practitioner undergoes multi-stage background checks, license verification, and clinical training before consultation approval.",
    iconName: "ShieldCheck",
  },
  {
    id: "organic-purity",
    title: "100% Traceable Herbal Sources",
    description: "From farm to formulation, our medicines are checked for heavy metals, pesticides, and microbial purity in certified laboratories.",
    iconName: "CheckCircle2",
  },
];

export const DOCTORS: Doctor[] = [
  {
    id: "doc-1",
    name: "Dr. Sanjeev Bhaskar",
    specialty: "Senior Ayurvedic Physician",
    image: "/images/dr_sanjeev_bhaskar.png",
    qualifications: ["BAMS (University of Delhi)", "MD (Ayurveda - Kayachikitsa)"],
    experience: 18,
    rating: 4.9,
    reviewsCount: 3240,
    availability: "Available Tomorrow",
    fee: 499,
  },
  {
    id: "doc-2",
    name: "Dr. Ananya Roy",
    specialty: "Homeopathic Consultant",
    image: "/images/dr_ananya_roy.png",
    qualifications: ["BHMS (NIH Kolkata)", "MD (Homeopathy - Repertory)"],
    experience: 14,
    rating: 4.8,
    reviewsCount: 2150,
    availability: "Available Today",
    fee: 450,
  },
  {
    id: "doc-3",
    name: "Dr. Madhavan Pillai",
    specialty: "Panchakarma & Spine Specialist",
    image: "/images/dr_madhavan_pillai.png",
    qualifications: ["BAMS (Kerala Ayurveda Academy)", "MD (Panchakarma)"],
    experience: 22,
    rating: 4.95,
    reviewsCount: 4580,
    availability: "Available in 30 Mins",
    fee: 599,
  },
  {
    id: "doc-4",
    name: "Dr. Priya Deshmukh",
    specialty: "Women's Health & Gynaecology (Ayur)",
    image: "/images/dr_priya_deshmukh.png",
    qualifications: ["BAMS (Pune)", "MS (Prasuti Tantra & Stri Roga)"],
    experience: 11,
    rating: 4.85,
    reviewsCount: 1890,
    availability: "Available Today",
    fee: 499,
  },
];

export const PATIENT_STORIES: PatientStory[] = [
  {
    id: "story-1",
    patientName: "Rajesh Kumar",
    age: 45,
    location: "Mumbai, Maharashtra",
    rating: 5,
    treatmentReceived: "Chronic Acidity & IBS Treatment",
    duration: "3 Months",
    reviewText: "I was suffering from IBS for over 5 years. Standard medications only gave temporary relief. Ojas Sanjivani's customized diet and herbal pills completely cured my digestion in 3 months. Truly life-changing!",
    image: "/images/patient-rajesh.jpg",
  },
  {
    id: "story-2",
    patientName: "Meera Nair",
    age: 38,
    location: "Bangalore, Karnataka",
    rating: 5,
    treatmentReceived: "Rheumatoid Arthritis Homeopathy Care",
    duration: "6 Months",
    reviewText: "The joint stiffness in my hands was getting worse. Dr. Ananya's gentle homeopathic drops have drastically reduced the swelling and pain. I can write and garden again without discomfort.",
    image: "/images/patient-meera.jpg",
  },
  {
    id: "story-3",
    patientName: "Vikram Rathore",
    age: 52,
    location: "Jaipur, Rajasthan",
    rating: 5,
    treatmentReceived: "Diabetes & Fatigue Management Plan",
    duration: "4 Months",
    reviewText: "My blood sugar levels were fluctuating heavily. The wellness plan, combined with Ayurvedic formulations, stabilized my HbA1c from 8.2 to 6.4. I feel highly energetic throughout the day.",
    image: "/images/patient-vikram.jpg",
  },
];

export const MEDICINE_PRODUCTS: MedicineProduct[] = [
  {
    id: "med-1",
    name: "Organic Ashwagandha Gold Caps",
    brand: "Ojas Wellness",
    category: "ayurveda",
    price: 380,
    originalPrice: 450,
    rating: 4.8,
    reviewsCount: 1420,
    image: "/images/product-ashwagandha.jpg",
    tag: "Best Seller",
    description: "Premium KSM-66 Ashwagandha extract with pure gold bhasma to fight stress, boost immunity, and enhance vitality.",
  },
  {
    id: "med-2",
    name: "Triphala Gut Detox Powder",
    brand: "Sanjivani Herbs",
    category: "ayurveda",
    price: 199,
    originalPrice: 250,
    rating: 4.7,
    reviewsCount: 890,
    image: "/images/product-triphala.jpg",
    tag: "100% Organic",
    description: "Balanced formulation of Amla, Haritaki, and Vibhitaki to regulate bowel movements and deeply detoxify the GI tract.",
  },
  {
    id: "med-3",
    name: "Arnica Hair Vitality Oil",
    brand: "Ojas Pharmacy",
    category: "homeopathy",
    price: 275,
    originalPrice: 320,
    rating: 4.6,
    reviewsCount: 650,
    image: "/images/product-arnica-oil.jpg",
    description: "Non-greasy, premium homeopathic blend enriched with Arnica Montana, Jaborandi, and Cantharis to prevent hair loss.",
  },
  {
    id: "med-4",
    name: "Ayush 64 Immunity Booster",
    brand: "Ojas Wellness",
    category: "ayurveda",
    price: 290,
    rating: 4.9,
    reviewsCount: 2110,
    image: "/images/product-ayush64.jpg",
    tag: "Clinical Grade",
    description: "Scientifically validated Ayurvedic formulation to boost respiratory immunity and defend against viral infections.",
  },
];

export const FAQS: FAQItem[] = [
  {
    id: "faq-1",
    question: "How do I choose between Ayurveda and Homeopathy?",
    answer: "Ayurveda focuses on balancing the three bio-energies (Vata, Pitta, Kapha) using diet, herbs, and therapies to address root causes. Homeopathy uses micro-dosed natural substances to trigger the body's self-healing mechanisms. If you are unsure, our Wellness Assistant can analyze your symptoms and recommend the most effective treatment pathway.",
    category: "general",
  },
  {
    id: "faq-2",
    question: "Are the doctors on Ojas Sanjivani certified?",
    answer: "Absolutely. All doctors are fully verified by our clinical board. Ayurvedic doctors hold recognized BAMS/MD (Ayurveda) degrees and Homeopathic doctors hold BHMS/MD (Homeopathy) qualifications. They are registered with central/state medical councils and have a minimum of 5 years of active clinical experience.",
    category: "consultation",
  },
  {
    id: "faq-3",
    question: "How fast is medicine delivery?",
    answer: "We offer express shipping. In metro cities, medicines are delivered within 4 to 24 hours. For non-metros and remote locations, delivery takes 2 to 4 business days. All medicines are packed in temperature-stable, tamper-proof packages to maintain therapeutic potency.",
    category: "orders",
  },
  {
    id: "faq-4",
    question: "How does the Digital Wellness Assistant work?",
    answer: "Our digital assistant uses clinical reasoning models and medical ontologies. You answer a few simple questions regarding your symptoms, lifestyle, and digestion. It then compiles a preliminary symptom assessment, estimates your constitutional Prakriti (Ayurveda), and suggests the right doctor specialty.",
    category: "general",
  },
  {
    id: "faq-5",
    question: "Do you supply organic medicines?",
    answer: "Yes, all Ojas Sanjivani brand products are sourced from certified organic farms, free from chemical fertilizers and synthetic additives. Our external vendor products undergo strict batch-testing for purity, heavy metals, and shelf-life stability before listing.",
    category: "orders",
  },
];
